Backend/GeeksBakery/Controllers/AccountsController.cs
using GeeksBakery.ClientSite.Interfaces;
using GeeksBakery.Utilities.SystemConstants;
using GeeksBakery.ViewModels.Requests.System.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace GeeksBakery.ClientSite.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IUserService _userService;
        private readonly IConfiguration _configuration;

        public AccountsController(IUserService userService, IConfiguration configuration)
        {
            _userService = userService;
            _configuration = configuration;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            if (TempData["IsRegisterSuccess"] != null)
            {
                ViewBag.IsRegisterSuccess = true;
                TempData["IsRegisterSuccess"] = null;
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequest request)
        {
            ViewBag.IsLogin = true;
            if (!ModelState.IsValid)
            {
                ViewData["LoginRequest"] = request;
                return View("Index");
            }

            var response = await _userService.AuthenticateAsync(request);

            // return error to login view if login unsuccessul
            if (!response.IsSuccessed)
            {
                ModelState.AddModelError("", "Username or password is incorrect");
                ViewData["LoginRequest"] = request;

                return View("Index");
            }

            //Add token and session
            var userPrincipal = this.ValidateToken(response.ResultObj);

            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(1440),
                IsPersistent = false
            };
            HttpContext.Session.SetString(SystemConstants.AppSettings.Token, response.ResultObj);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, userPrincipal, authProperties);

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequest request)
        {
            ViewBag.IsLogin = false;

            if (!ModelState.IsValid)
            {
                ViewData["RegisterRequest"] = request;
                return View("Index");
            }
            var result = await _userService.RegisterAsync(request);
            if (!result.IsSuccessed)
            {
                ModelState.AddModelError("", result.Message);
                ViewData["RegisterRequest"] = request;
                return View("Index");
            }
            TempData["IsRegisterSuccess"] = true;

            return RedirectToAction("Index", "Accounts");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        private ClaimsPrincipal ValidateToken(string jwtToken)
        {
            IdentityModelEventSource.ShowPII = true;

            SecurityToken validatedToken;
            TokenValidationParameters validationParameters = new TokenValidationParameters();

            validationParameters.ValidateLifetime = true;

            validationParameters.ValidAudience = _configuration["Tokens:Issuer"];
            validationParameters.ValidIssuer = _configuration["Tokens:Issuer"];
            validationParameters.IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Tokens:Key"]));

            ClaimsPrincipal principal = new JwtSecurityTokenHandler().ValidateToken(jwtToken, validationParameters, out validatedToken);

            return principal;
        }
    }
}

Backend/GeeksBakery/ViewComponents/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeeksBakery.ClientSite.ViewComponents
{
    public class LoginViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Backend/GeeksBakery/ViewComponents/RegisterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeeksBakery.ClientSite.ViewComponents
{
    public class RegisterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Backend/GeeksBakery/Views/Accounts/Index.cshtml
@{
    Layout = null;
    ViewData["Title"] = "Login";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Geek's Bakery</title>
    <link rel="stylesheet" href="~/css/base.css" />
    <link rel="stylesheet" href="~/css/reset.css" />
    <link rel="stylesheet" href="~/css/login.css" />

    <link rel="icon" href="~/icons/favio.png" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet" />
</head>

<body>
    <div class="box">
        <div class="switch-button">
            <div id="switchButton" class="switch-button__switch"></div>
            <button id="switchToLogin" class="switch-button__button switch-button__button--active">
                Login
            </button>
            <button id="switchToRegister" class="switch-button__button">
                Register
            </button>
        </div>
        @if (ViewBag.IsRegisterSuccess == true)
        {
            <p style="  margin-top: 30px; text-align: center; color: #009200;">Register successful! Please log in.</p>
        }
        <div id="formInputGroup" class="form-group">
            @await Component.InvokeAsync("Login", ViewData["LoginRequest"])
            @await Component.InvokeAsync("Register", ViewData["RegisterRequest"])
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <partial name="_ValidationScriptsPartial">

        <script src="~/js/login.js"></script>
</body>
</html>