Backend/GeeksBakery/Controllers/CakesController.cs
using GeeksBakery.ClientSite.Interfaces;
using GeeksBakery.ClientSite.Models;
using GeeksBakery.ViewModels.Requests.Cake;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeeksBakery.ClientSite.Controllers
{
    public class CakesController : Controller
    {
        private readonly ICakeService _cakeService;
        private readonly ICategoryService _categoryService;

        public CakesController(ICakeService cakeService, ICategoryService categoryService)
        {
            _cakeService = cakeService;
            _categoryService = categoryService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] GetCakePagingRequest request)
        {
            request.Limit = 12;
            request.Page = request.Page > 0 ? request.Page : 1;

            var cakes = await _cakeService.GetPagingsAsync(request);
            var categories = await _categoryService.GetAllAsync();

            var viewModel = new CakesViewModel()
            {
                Cakes = cakes,
                Categories = categories
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var cakes = await _cakeService.GetByIdAsync(id);

            return View(cakes);
        }
    }
}

Backend/GeeksBakery/ViewComponents/HeaderViewComponent.cs
using GeeksBakery.ClientSite.Interfaces;
using GeeksBakery.ViewModels.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GeeksBakery.ClientSite.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly IUserService _userService;

        public HeaderViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public IViewComponentResult Invoke()
        {
            UserViewModel header = new UserViewModel();
            if (User.Identity.IsAuthenticated)
            {
                var identity = (ClaimsIdentity)User.Identity;
                IEnumerable<Claim> claims = identity.Claims;

                header = _userService.ClaimsToViewModelAsync(claims);
            }
            else
            {
                header = null;
            }
            return View(header);
        }
    }
}

Backend/GeeksBakery/Views/Shared/_Footer.cshtml
<!-- footer -->
<footer>
    <div class="footer container">

        <div class="footer__logo">
            <img src="~/img/logo.png" alt="footer logo" />
        </div>
        <div class="footer__lists">
            <div class="footer__list">
                <h6 class="footer__list__title">Categories</h6>
                <ul>
                    <li>
                        <a asp-controller="Cakes" asp-action="Index" asp-route-categoryids="1">Chocolate</a>
                    </li>
                    <li>
                        <a asp-controller="Cakes" asp-action="Index" asp-route-categoryids="2">Fruits</a>
                    </li>
                    <li>
                        <a asp-controller="Cakes" asp-action="Index" asp-route-categoryids="8">Strawberry</a>
                    </li>
                    <li>
                        <a asp-controller="Cakes" asp-action="Index" asp-route-categoryids="6">Vanilla</a>
                    </li>
                </ul>
            </div>
            <div class="footer__list">
                <h6 class="footer__list__title">About</h6>
                <ul>
                    <li>Geek's Bakery</li>
                    <li>Pham Chi Trung</li>
                    <li>pctrung1102@gmail.com</li>
                </ul>
            </div>
            <div class="footer__list">
                <h6 class="footer__list__title">Social</h6>
                <div class="footer__list__social">
                    <a target="_blank" href="https://www.facebook.com/trungxi.it">
                        <img src="~/icons/facebook.svg" alt="facebook icon" />
                    </a>
                    <a target="_blank" href="https://github.com/TrungXiIT">
                        <img src="~/icons/github.svg" alt="github icon" />
                    </a>
                    <a target="_blank" href="https://www.linkedin.com/in/trung-ph%E1%BA%A1m-101b871a2/">
                        <img src="~/icons/linkedin.svg" alt="linkedin icon" />
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid footer__copyright">
        <p>Copyright © 2021 Pham Chi Trung</p>
    </div>
</footer>
<!-- end footer -->

Backend/GeeksBakery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Geek's Bakery</title>

    <link rel="icon" href="~/icons/favio.png" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet" />

    <link rel="stylesheet" href="~/css/reset.css" />
    <link rel="stylesheet" href="~/css/base.css" />
    <link rel="stylesheet" href="~/css/header.css" />
    <link rel="stylesheet" href="~/css/footer.css" />

    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <div id="loading-screen">
        <div class="spinner">
            <div class="double-bounce1"></div>
            <div class="double-bounce2"></div>
        </div>
    </div>

    @await Component.InvokeAsync("Header")
    <main>
        @RenderBody()
    </main>

    <div class="separate"></div>

    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script type="text/javascript" src="~/js/app.js"></script>
    <script type="text/javascript" src="~/js/slider.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Backend/GeeksBakery/Views/Shared/_PageNumber.cshtml
@model GeeksBakery.ClientSite.Models.PageNumberModel

@{
    int leftPageArrowNumber = Model.Page - 1 > 0 ? Model.Page - 1 : 0;
    int rightPageArrowNumber = Model.Page + 1 <= Model.PageCount ? Model.Page + 1 : 9999;
}
<div class="paging-numbers">
    <!-- left arrow svg -->
    @if (leftPageArrowNumber > 0)
    {
        <a asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-keyword="@Model.Keyword" asp-route-page="@leftPageArrowNumber">
            <svg class="paging-number-left-arrow paging-arrow"
                 width="34"
                 height="35"
                 viewBox="0 0 34 35"
                 fill="none"
                 xmlns="http://www.w3.org/2000/svg">
                <circle cx="17"
                        cy="17.9402"
                        r="16.5"
                        transform="rotate(-180 17 17.9402)"
                        stroke="#848484" />
                <path d="M12.2387 16.935L18.8388 11.1495C19.1571 10.8704 19.6732 10.8704 19.9915 11.1495L20.7613 11.8242C21.079 12.1028 21.0797 12.5543 20.7626 12.8335L15.5319 17.4402L20.7626 22.0469C21.0797 22.3261 21.079 22.7776 20.7613 23.0561L19.9915 23.7309C19.6732 24.0099 19.1571 24.0099 18.8388 23.7309L12.2387 17.9454C11.9204 17.6664 11.9204 17.214 12.2387 16.935Z"
                      fill="#848484" />
            </svg>
        </a>
    }
    else
    {
        <svg class="paging-number-left-arrow"
             width="34"
             height="35"
             viewBox="0 0 34 35"
             fill="none"
             xmlns="http://www.w3.org/2000/svg">
            <circle cx="17"
                    cy="17.9402"
                    r="16.5"
                    transform="rotate(-180 17 17.9402)"
                    stroke="#848484" />
            <path d="M12.2387 16.935L18.8388 11.1495C19.1571 10.8704 19.6732 10.8704 19.9915 11.1495L20.7613 11.8242C21.079 12.1028 21.0797 12.5543 20.7626 12.8335L15.5319 17.4402L20.7626 22.0469C21.0797 22.3261 21.079 22.7776 20.7613 23.0561L19.9915 23.7309C19.6732 24.0099 19.1571 24.0099 18.8388 23.7309L12.2387 17.9454C11.9204 17.6664 11.9204 17.214 12.2387 16.935Z"
                  fill="#848484" />
        </svg>
    }
    <!-- end left arrow svg -->
    @if(Model.Page > Model.PageCount)
    {
        Model.Page = Model.PageCount;
    }else if (Model.Page < 1)
    {
        Model.Page = 1;
    }
     @{ 
         bool leftDotFlag = false;
         bool rightDotFlag = false;
     }
    @for (var i = 1; i <= Model.PageCount; i++)
    {
        @if (Model.Page - i >= 2)
        {
            if (i <= 1)
            {
                <a asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-page="@i" asp-route-keyword="@Model.Keyword" class="paging-number @(Model.Page == i ? "paging-number--active" : "")">
                    @i
                </a>
            }
            else if (!leftDotFlag)
            {
                <span class="paging-number" style="cursor:default">
                    ...
                </span>
                leftDotFlag = !leftDotFlag;
            }

        }
        else if (Model.Page - i <= -2)
        {
            if (i >= Model.PageCount)
            {
                <a asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-page="@i" asp-route-keyword="@Model.Keyword" class="paging-number @(Model.Page == i ? "paging-number--active" : "")">
                    @i
                </a>
            }
            else if (!rightDotFlag)
            {

                <span class="paging-number" style="cursor:default">
                    ...
                </span>
                rightDotFlag = !rightDotFlag;
            }
        }
        else if (Math.Abs(Model.Page - i) <= 2)
        {
            <a asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-page="@i" asp-route-keyword="@Model.Keyword" class="paging-number @(Model.Page == i ? "paging-number--active" : "")">
                @i
            </a>
        }

    }

    <!-- right arrow svg -->
    @if (rightPageArrowNumber <= Model.PageCount)
    {
        <a asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-keyword="@Model.Keyword" asp-route-page="@rightPageArrowNumber">
            <svg class="paging-number-right-arrow paging-arrow"
                 width="34"
                 height="34"
                 viewBox="0 0 34 34"
                 fill="none"
                 xmlns="http://www.w3.org/2000/svg">
                <circle cx="17" cy="17" r="16.5" stroke="#848484" />
                <path d="M21.7613 18.0052L15.1612 23.7907C14.8429 24.0698 14.3268 24.0698 14.0085 23.7907L13.2387 23.1159C12.921 22.8374 12.9203 22.3859 13.2374 22.1067L18.4681 17.5L13.2374 12.8933C12.9203 12.6141 12.921 12.1626 13.2387 11.8841L14.0085 11.2093C14.3268 10.9302 14.8429 10.9302 15.1612 11.2093L21.7613 16.9948C22.0796 17.2738 22.0796 17.7262 21.7613 18.0052Z"
                      fill="#848484" />
            </svg>
        </a>
    }
    else
    {
        <svg class="paging-number-right-arrow"
             width="34"
             height="34"
             viewBox="0 0 34 34"
             fill="none"
             xmlns="http://www.w3.org/2000/svg">
            <circle cx="17" cy="17" r="16.5" stroke="#848484" />
            <path d="M21.7613 18.0052L15.1612 23.7907C14.8429 24.0698 14.3268 24.0698 14.0085 23.7907L13.2387 23.1159C12.921 22.8374 12.9203 22.3859 13.2374 22.1067L18.4681 17.5L13.2374 12.8933C12.9203 12.6141 12.921 12.1626 13.2387 11.8841L14.0085 11.2093C14.3268 10.9302 14.8429 10.9302 15.1612 11.2093L21.7613 16.9948C22.0796 17.2738 22.0796 17.7262 21.7613 18.0052Z"
                  fill="#848484" />
        </svg>

    }

    <!-- end right arrow svg -->
</div>