Backend/GeeksBakery/Models/CakesViewModel.cs
using GeeksBakery.ViewModels.Common;
using GeeksBakery.ViewModels.ViewModels;
using System.Collections.Generic;

namespace GeeksBakery.ClientSite.Models
{
    public class CakesViewModel
    {
        public PagedResult<CakeViewModel> Cakes;
        public List<CategoryViewModel> Categories;
        //private PagedResult<CakeViewModel> _cakes;
        //private List<CategoryViewModel> _categories;

        //public PagedResult<CakeViewModel> Cakes
        //{
        //    get => _cakes == null ? new PagedResult<CakeViewModel>() { Items = new List<CakeViewModel>() } : _cakes;
        //    set => _cakes = value;
        //}

        //public List<CategoryViewModel> Categories
        //{
        //    get => _categories == null ? new List<CategoryViewModel>() : _categories;
        //    set => _categories = value;
        //}
    }
}

Backend/GeeksBakery/Controllers/CakesController.cs
using GeeksBakery.ClientSite.Interfaces;
using GeeksBakery.ClientSite.Models;
using GeeksBakery.ViewModels.Requests.Cake;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeeksBakery.ClientSite.Controllers
{
    public class CakesController : Controller
    {
        private readonly ICakeService _cakeService;
        private readonly ICategoryService _categoryService;

        public CakesController(ICakeService cakeService, ICategoryService categoryService)
        {
            _cakeService = cakeService;
            _categoryService = categoryService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] GetCakePagingRequest request)
        {
            request.Limit = 12;
            request.Page = request.Page > 0 ? request.Page : 1;

            var cakes = await _cakeService.GetPagingsAsync(request);
            var categories = await _categoryService.GetAllAsync();

            var viewModel = new CakesViewModel()
            {
                Cakes = cakes,
                Categories = categories
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var cakes = await _cakeService.GetByIdAsync(id);

            return View(cakes);
        }
    }
}

Backend/GeeksBakery/Controllers/ReviewsController.cs
using GeeksBakery.ClientSite.Interfaces;
using GeeksBakery.ViewModels.Requests.Review;
using GeeksBakery.ViewModels.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GeeksBakery.ClientSite.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IUserService _userService;
        private readonly IReviewService _reviewService;

        public ReviewsController(IUserService userService, IReviewService reviewService)
        {
            _userService = userService;
            _reviewService = reviewService;
        }

        [HttpPost("{cakeId}")]
        public async Task<IActionResult> Add(int cakeId, string returnUrl, ReviewCreateRequest request)
        {
            returnUrl = returnUrl == null ? "" : returnUrl;
            UserViewModel user = new UserViewModel();
            if (User.Identity.IsAuthenticated)
            {
                var identity = (ClaimsIdentity)User.Identity;
                IEnumerable<Claim> claims = identity.Claims;

                user = _userService.ClaimsToViewModelAsync(claims);

                request.UserId = user.Id;

                var isAddSuccess = await _reviewService.AddAsync(request);
            }
            return Redirect(returnUrl);
        }
    }
}

Backend/GeeksBakery/ViewComponents/CakeViewComponent.cs
using GeeksBakery.ViewModels.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeeksBakery.ClientSite.ViewComponents
{
    public class CakeViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(CakeViewModel cake)
        {
            return View(cake);
        }
    }
}

Backend/GeeksBakery/Views/Cakes/Details.cshtml
@model CakeViewModel
@{
    ViewData["Title"] = "Detail";
}
@section Styles{
    <link rel="stylesheet" href="~/css/details.css">
}

@if (Model == null)
{
    <h1>Not found cakes</h1>
}
else
{
    <div class="separate"></div>

    <!-- wrapper detail seller -->
    <div class="container">
        <h3 class="details__title">
            <a asp-controller="Cakes" asp-action="Index">Cakes</a>>
            <a asp-controller="Cakes" asp-action="Index" asp-route-categoryids="@Model.CategoryId">@Model.CategoryName</a>
        </h3>
    </div>
    <section class="container-fluid details-background">
        <div class="wrapper">
            <section class="container details noselect">
                <div class="details__item">
                    <div class="details__item-images">
                        <div class="details__item-image">
                        <img id="mainImageId" 
                         src="@(Model.CakeImages.IsSafe() ? Model.CakeImages.FirstOrDefault().FileUrl : SystemConstants.DEFAULT_CAKE_IMAGE_URL)"
                         alt="@(Model.CakeImages.IsSafe() ? Model.CakeImages.FirstOrDefault().Caption : SystemConstants.DEFAULT_CAKE_IMAGE_CAPTION)" />
                        </div>
                        <div class="details__items-small-images">
                            @foreach (var image in Model.CakeImages)
                            {
                                 <img  class="details__items-small-image" onclick="showImage('@image.FileUrl')" style="cursor: pointer" src="@image.FileUrl" alt="@image.Caption" /> 
                            }
                        </div>
                    </div>
                    <div class="details__item-info">
                        <div>
                            <h6 class="details__item-info__name">
                                @Model.Name
                            </h6>
                            <p class="details__item-info__category">Category: @Model.CategoryName</p>
                            <p class="details__item-info__description line-clamp-5">
                                @Model.Description
                            </p>
                        </div>
                        <div>
                            <div class="details__item-info__price">@Model.Price.ToVND()</div>
                            <div class="details__item-info__original-price">@Model.OriginalPrice.ToVND()</div>
                        </div>
                        <button class="btn btn--primary">Add to cart +</button>
                    </div>
                </div>
            </section>
        </div>
    </section>
    <!-- end wrapper detail seller-->

    <section class="wrapper">
        <h3 class="container details__title">Reviews</h3>
        <div class="container reviews">
            <div class="reviews__item reviews__stars">
                <div class="reviews__stars-total">
                    <div class="reviews__stars-total__title">@Math.Round(Model.AvgStar, 1)</div>
                    <div class="stars-row">
                        <img src="~/icons/star.svg" alt="star icon" />
                        <img src="~/icons/star.svg" alt="star icon" />
                        <img src="~/icons/star.svg" alt="star icon" />
                        <img src="~/icons/star.svg" alt="star icon" />
                        <img src="~/icons/star.svg" alt="star icon" />
                    </div>
                    <div class="reviews__stars-total__quantity">
                        @Model.Reviews.Count @(Model.Reviews.Count>1? "reviews" : "review")
                    </div>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <form method="post" asp-controller="Reviews" asp-action="Add" asp-route-cakeId="@Model.Id"
                          asp-route-returnurl="/cakes/details/@Model.Id" class="reviews__stars__comment">
                        <textarea required id="comment" name="comment" cols="30" rows="5" style="resize: none"
                                  placeholder="Write your comment..."></textarea>
                        <div class="reviews__stars__comment__rating">
                            <div class="stars-row">
                                <input required hidden type="radio" name="star" value="1" id="star1" />
                                <input required hidden type="radio" name="star" value="2" id="star2" />
                                <input required hidden type="radio" name="star" value="3" id="star3" />
                                <input required hidden type="radio" name="star" value="4" id="star4" />
                                <input required hidden type="radio" name="star" value="5" id="star5" />
                                <label for="star1"><img id="starImage1" src="~/icons/empty-star.svg" alt="star icon" /></label>
                                <label for="star2"><img id="starImage2" src="~/icons/empty-star.svg" alt="star icon" /></label>
                                <label for="star3"><img id="starImage3" src="~/icons/empty-star.svg" alt="star icon" /></label>
                                <label for="star4"><img id="starImage4" src="~/icons/empty-star.svg" alt="star icon" /></label>
                                <label for="star5"><img id="starImage5" src="~/icons/empty-star.svg" alt="star icon" /></label>
                            </div>
                            <div class="reviews__stars__comment__rating-stars">
                                <button id="submitReview" class="btn btn--primary">Submit</button>
                            </div>
                        </div>
                    </form>
                }
                else
                {
                    <p>
                        Please
                        <a style="text-align:center; font-weight:bold" asp-controller="Accounts" asp-action="Index">
                            login
                        </a>
                        to review this cake!
                    </p>
                }
            </div>
            <div class="reviews__item reviews__comments">
                @if (Model.Reviews.IsSafe())
                {
                    @foreach (var review in Model.Reviews)
                    {
                        <div class="reviews__comment">
                            <div class="reviews__comment__avatar">
                                <img src="@review.UserAvatar" alt="User Avatar" />
                            </div>
                            <div class="reviews__comment__content">
                                <div class="reviews__comment__content__info">
                                    <div class="reviews__comment__content__info-name">
                                        @review.UserName
                                    </div>
                                    <div class="reviews__comment__content__info-star-time">
                                        <div class="stars-row-small">
                                            @for (var i = 1; i <= review.Star; i++)
                                            {
                                                <img src="~/icons/star.svg" alt="star icon" />
                                            }
                                            @for (var i = review.Star + 1; i <= 5; i++)
                                            {
                                                <img src="~/icons/empty-star.svg" alt="star icon" />
                                            }
                                        </div>
                                        <div class="reviews__comment__content__info-time">
                                            @review.DateCreated.ToString()
                                        </div>
                                    </div>
                                </div>
                                <div class="reviews__comment__content__content">
                                    @review.Comment
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <p style="text-align:center">There are no comments yet</p>
                }
            </div>
        </div>
    </section>

    @section Scripts{
        <script>
            $(document).ready(function () {
                $(stars[1]).on("click", () => { selectStar(1); });
                $(stars[2]).on("click", () => { selectStar(2); });
                $(stars[3]).on("click", () => { selectStar(3); });
                $(stars[4]).on("click", () => { selectStar(4); });
                $(stars[5]).on("click", () => { selectStar(5); });

                $('#submitReview').prop('disabled', true);
                $('#submitReview').addClass("btn--disabled");
                $('#comment').keyup(function () {
                    checkSubmitState();
                });
            })

            var stars = ["", "#star1", "#star2", "#star3", "#star4", "#star5"];
            var starImages = ["", "#starImage1", "#starImage2", "#starImage3", "#starImage4", "#starImage5"];
            var isChecked = false;
            var isCommented = false;

            function selectStar(index) {
                isChecked = true;
                if (index < 1) {
                    index = 1;
                }
                if (index > 5) {
                    index = 5;
                }

                for (var i = 1; i <= index; i++) {
                    $(starImages[i]).attr("src", "/icons/star.svg");
                }
                for (var i = index + 1; i <= 5; i++) {
                    $(starImages[i]).attr("src", "/icons/empty-star.svg");
                }
                checkSubmitState();
            }

            function checkSubmitState() {
                if ($('#comment').val() === "") {
                    isCommented = false
                } else {
                    isCommented = true;
                }

                if (isCommented == true && isChecked == true) {
                    $('#submitReview').prop('disabled', false);
                    $('#submitReview').removeClass("btn--disabled");
                } else if (isCommented == false || isChecked == false) {
                    $('#submitReview').prop('disabled', true);
                    $('#submitReview').addClass("btn--disabled");
                }
            }

            function showImage(url) {
                $('#mainImageId').attr("src", url);
            }
        </script>
    }
}

Backend/GeeksBakery/Views/Cakes/Index.cshtml
@model CakesViewModel
@{
    ViewData["Title"] = "Cakes";
}

@section Styles {
    <link rel="stylesheet" href="~/css/home.css">
}

<div class="separate"></div>
<!-- wrapper sweeties -->
<div class="wrapper  ">
    <section class="container sweeties">
        <h3 class="title">Cakes</h3>
        @if (Model.Categories != null)
        {
            <ul class="cakes__category">
                @foreach (var category in Model.Categories)
                {
                    <li>
                        <a asp-controller="Cakes" asp-action="Index" asp-route-categoryids="@category.Id">@category.Name</a>
                    </li>
                }
            </ul>
        }

        @if (Model.Cakes != null)
        {
            @if (!String.IsNullOrEmpty(Model.Cakes.Keyword))
            {
                <div style="align-self: flex-start; margin-bottom:20px; text-align:left;">
                    Search results for:
                    <b>@Model.Cakes.Keyword</b>
                </div>
            }
            @if (Model.Cakes.CategoryNames.Any(x => x.Contains("")))
            {
                <div style="align-self: flex-start; margin-bottom: 20px;">
                    Category:
                    @for (var i = 0; i < Model.Cakes.CategoryNames.Count; i++)
                    {
                        <b>@(Model.Cakes.CategoryNames[i])</b>
                        @if (i < Model.Cakes.CategoryNames.Count - 1)
                        {
                            <span>, </span>
                        }
                    }
                </div>
            }

            <div class="sweeties__items">
                @if (Model.Cakes.Items.IsSafe())
                {
                    @foreach (var cake in Model.Cakes.Items)
                    {
                        @await Component.InvokeAsync("Cake", cake);
                    }

                }
                else
                {
                    <p>Not found any cakes</p>
                }
            </div>

            <!-- Page number -->

            PageNumberModel pageModel = new PageNumberModel
            {
                Page = Model.Cakes.Page,
                PageCount = Model.Cakes.PageCount,
                Action = "Index",
                Controller = "Cakes",
                Keyword = Model.Cakes.Keyword
            };
            <partial name="_PageNumber" model="@pageModel" />
        }
        else
        {
            <p>Not found any cakes</p>
        }
    </section>
</div>
<!-- end wrapper sweeties -->